### ISSUE TITLE
Dúvida último exercício

### ISSUE THREAD

**Issue by paschoal-artur** [ProfRonan/matrizes-e-vetores-paschoal-artur#2]
Professor, a file requirements.txt é para a gente fazer o que exatamente?

**Comment by SeuRonao** [comment]
É pra ser só um arquivo texto vazio nesse exercício.

**Comment by SeuRonao** [comment]
Quando existem alguns requisitos para o programa rodar que não vem
embutidos no interpretador, é uma convenção geral criar esse arquivo e
colocar elas lá.

Por exemplo, o pandas para manipular tabelas e dados seria uma dependência
caso fosse necessário utilizar eles em alguma função.

**Comment by paschoal-artur** [comment]
Certo, professor. Muito obrigado!
