### ISSUE TITLE
Estou usando numpy

### ISSUE THREAD

**Issue by paschoal-artur** [ProfRonan/matrizes-e-vetores-paschoal-artur#3]

**Comment by SeuRonao** [comment]
Para usar o numpy nos testes do github você vai ter que alterar o arquivo `requirements.txt` para que ele possa ser instalado para usar no servidor.
Basta colocar uma linha no arquivo com a palavra `numpy`.

**Comment by paschoal-artur** [comment]
Ok professor. Muito obrigado!
