### ISSUE TITLE
Issue que o senhor pediu para realizar

### ISSUE THREAD

**Issue by paschoal-artur** [ProfRonan/matrizes-e-vetores-paschoal-artur#4]
Professor dei o commit no código e aqui estou abrindo a issue para o senhor poder realizar a checagem
Atenciosamente, 
Artur Saraiva Paschoal

**Comment by paschoal-artur** [comment]
Vou comentar os erros que mandei no email, aqui na sessão de comentários, para ficar melhor a sua visualização

1° email: Professor, estou importando a pasta tipos.py para utilizar as variáveis e simplificar o código. Porém o pylance me indica um erro, "Import tipos could not be resolved" porém eu creio estar utilizando da maneira correta. Segue a forma como estou utilizando o import:
from tipos import Escalar, Matriz

2° email: Estou tentando testar o meu programa e ele fica dando erro diversas vezes. Mas não acho o erro no meu código e o terminal me lança a seguinte mensagem, exemplo do teste da soma de vetores:

ERROR: vector.test_soma (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: vector.test_soma
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/artur/matrizes-e-vetores-paschoal-artur/test/vector/test_soma.py", line 6, in <module>
    from vector import soma
ImportError: cannot import name 'soma' from 'vector' (/home/artur/matrizes-e-vetores-paschoal-artur/test/vector/__init__.py)

O erro está no meu programa ou está no seu teste? Aparece essa falha de importação em algumas funções, não entendi aonde é o erro.

**Comment by SeuRonao** [comment]
Como você está fazendo para iniciar os testes?
Aqui no meu computador e no proprio github esse erro não aparece, aparecem outros, mas não esses relatados.
Amanhã na aula, podemos ver juntos essa questão.

**Comment by SeuRonao** [comment]
Na realidade, ví quais eram os erros. Respondi no feedback. @paschoal-artur
