### ISSUE TITLE
Dúvida no código

### ISSUE THREAD

**Issue by paschoal-artur** [ProfRonan/matrizes-e-vetores-paschoal-artur#5]
Professor, troquei algumas coisas e analisei o código e ainda sim não consigo achar o erro. E os testes não estão mais aparecendo para mim no gitHub então não consigo analisar o que ele rodou e deu erro... O Senhor pode me ajudar?
Outra coisa, no meu arquivo de requirements.txt o senhor anexou o necessário para rodar os formatadores, como faço para utilizá-los direitinho, o Sr pode me explicar?

**Comment by SeuRonao** [comment]
Respondi algumas das dúvidas em #1 
No caso do `requirements.txt` ele tem as dependências do seu projeto.
Se o python não tiver com essas bibliotecas instaladas, dá para instalar todas elas usando `pip install -r requirements.txt` que o `pip` instala todos os pacotes listados.

**Comment by paschoal-artur** [comment]
Ok, obrigador professor!
